services:

  sporter_api:
    build: 
      context: ./
      dockerfile:  ./Dockerfile
    container_name: ${API_CONTAINER_NAME}
    volumes:
      - ${HOST_FILES_DIR}:${FILES_DIR}
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_DRIVERNAME=${MYSQL_DRIVERNAME}
      - APP_ADMIN_PASS=${APP_ADMIN_PASS}
      - APP_ADMIN_NAME=${APP_ADMIN_NAME}
      - APP_ADMIN_EMAIL=${APP_ADMIN_EMAIL}
      - FILES_DIR=${FILES_DIR}
    ports:
      - 5000:5000
    depends_on:
      sporter_db:
        condition: service_healthy
    networks:
      - backend

  sporter_db:
    image: mysql:latest
    container_name: ${DB_CONTAINER_NAME}
    volumes:
      - database_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 3
    networks:
      - backend

volumes:
  database_volume:
    name: ${API_DATABASE_VOLUME}

networks:
  backend:
